version: '2'

services:
  web:
    image: andrewhamon/caddy
    environment:
      - LE_EMAIL=andrew@hamon.cc
      - WEBHOOK_SECRET=${WEBHOOK_SECRET}
    ports:
      - "80:80"
      - "443:443"
    restart: always
